name: audiolm_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip<24.1
  - pip:
      - pip<24.1
      - tensorboardX
      - accelerate>=0.24.0
      - beartype>=0.16.1
      - einops>=0.7.0
      - ema-pytorch>=0.2.2
      - encodec
      - fairseq
      - wandb
      - gateloop-transformer>=0.2.3
      - hyper-connections>=0.1.8
      - joblib
      - local-attention>=1.9.0
      - pytorch-warmup
      - scikit-learn
      - sentencepiece
      - torch>=2.1
      - torchaudio
      - transformers
      - tqdm
      - vector-quantize-pytorch>=1.19.3
